# Generated by Django 5.0.14 on 2026-01-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "baseline_weekly_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Weekly baseline screen time allocated each Monday",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "children",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScreenTimeGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Goal name (e.g., 'Math Practice', 'Reading')",
                        max_length=200,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("binary", "Binary (Earned/Not Earned)"),
                            ("tracked", "Tracked (Hours/Minutes)"),
                        ],
                        default="binary",
                        help_text="Type of goal: binary (done/not done) or tracked (time-based)",
                        max_length=20,
                    ),
                ),
                (
                    "reward_minutes",
                    models.PositiveIntegerField(
                        help_text="Screen time reward in minutes for completing this goal"
                    ),
                ),
                (
                    "reward_per_hour",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Reward minutes per hour for tracked goals (e.g., 30 minutes screen time per hour of reading)",
                    ),
                ),
                (
                    "bonus_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Additional bonus minutes for completing without being asked",
                    ),
                ),
                (
                    "target_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Target minutes for tracked goals (e.g., 120 for 2 hours of reading)",
                    ),
                ),
                (
                    "applies_to_days",
                    models.CharField(
                        default="mon,tue,wed,thu,fri,sat,sun",
                        help_text="Comma-separated days (mon,tue,wed,thu,fri,sat,sun)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display for goals"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "children",
                    models.ManyToManyField(
                        db_table="tracker_goal_children",
                        help_text="Children this goal applies to",
                        related_name="goals",
                        to="tracker.child",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdhocReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.PositiveIntegerField(help_text="Minutes rewarded")),
                (
                    "reason",
                    models.CharField(help_text="Reason for the reward", max_length=200),
                ),
                (
                    "awarded_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date the reward was given"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adhoc_rewards",
                        to="tracker.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "awarded_date"],
                        name="tracker_adh_child_i_6e9ec9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the tracking")),
                (
                    "status",
                    models.CharField(
                        choices=[("earned", "Earned"), ("not_earned", "Not Earned")],
                        default="not_earned",
                        max_length=20,
                    ),
                ),
                (
                    "minutes_earned",
                    models.PositiveIntegerField(
                        default=0, help_text="Minutes of screen time earned"
                    ),
                ),
                (
                    "actual_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Actual minutes spent on tracked goals (e.g., 90 minutes of reading)",
                    ),
                ),
                (
                    "bonus_earned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the bonus was earned (done without being asked)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about the day's performance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        help_text="Child this tracking belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_trackings",
                        to="tracker.child",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_trackings",
                        to="tracker.screentimegoal",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "goal"],
                "indexes": [
                    models.Index(
                        fields=["child", "date", "goal"],
                        name="tracker_dai_child_i_510029_idx",
                    ),
                    models.Index(
                        fields=["goal", "date"], name="tracker_dai_goal_id_fb5531_idx"
                    ),
                ],
                "unique_together": {("child", "goal", "date")},
            },
        ),
    ]
