# Generated by Django 5.0.14 on 2026-01-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdhocPenalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.PositiveIntegerField(help_text="Minutes penalized")),
                (
                    "reason",
                    models.CharField(
                        help_text="Reason for the penalty", max_length=200
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date the penalty was applied"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adhoc_penalties",
                        to="tracker.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "applied_date"],
                        name="tracker_adh_child_i_e60f15_idx",
                    )
                ],
            },
        ),
    ]
