# Generated by Django 5.0.14 on 2026-01-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_add_adhocpenalty_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adhocpenalty",
            options={
                "ordering": ["-applied_date", "-created_at"],
                "verbose_name_plural": "penalties",
            },
        ),
    ]
