# Generated by Django 5.0.14 on 2026-01-22 14:58

from django.db import migrations, models


def drop_child_fk_index(apps, schema_editor):
    """
    MySQL auto-generates an index for the old child FK. When Django later tries
    to recreate a missing FK index during AlterUniqueTogether, MySQL can raise
    a duplicate index error. Pre-drop the old index if it exists (MySQL only).
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    try:
        schema_editor.execute("ALTER TABLE tracker_screentimegoal DROP INDEX tracker_screentimegoal_child_id_ea368193;")
    except Exception:
        # If the index name differs or is already gone, ignore; migration continues.
        pass


def migrate_child_to_children(apps, schema_editor):
    """
    Migrate existing child ForeignKey to children ManyToMany.
    Also merge duplicate goals that have the same name and settings.
    """
    ScreenTimeGoal = apps.get_model('tracker', 'ScreenTimeGoal')
    DailyTracking = apps.get_model('tracker', 'DailyTracking')
    
    # First pass: group goals by their attributes (excluding child)
    goal_groups = {}
    for goal in ScreenTimeGoal.objects.all():
        # Create a key based on goal attributes
        key = (
            goal.name,
            goal.goal_type,
            goal.reward_minutes,
            goal.reward_per_hour,
            goal.bonus_minutes,
            goal.target_minutes,
            goal.applies_to_days,
            goal.is_active,
        )
        
        if key not in goal_groups:
            goal_groups[key] = []
        goal_groups[key].append(goal)
    
    # Second pass: merge duplicate goals
    for key, goals in goal_groups.items():
        if len(goals) == 1:
            # Single goal - just add its child to the new ManyToMany field
            goal = goals[0]
            goal.children.add(goal.child_id)
        else:
            # Multiple goals with same attributes - merge them
            # Keep the first goal as the canonical one
            primary_goal = goals[0]
            
            # Add all children to the primary goal
            for goal in goals:
                primary_goal.children.add(goal.child_id)
            
            # Migrate DailyTracking entries from duplicate goals to primary goal
            for goal in goals[1:]:
                # Update all DailyTracking entries to point to the primary goal
                DailyTracking.objects.filter(goal=goal).update(goal=primary_goal)
                # Delete the duplicate goal
                goal.delete()


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - split multi-child goals back into per-child goals.
    """
    ScreenTimeGoal = apps.get_model('tracker', 'ScreenTimeGoal')
    
    for goal in ScreenTimeGoal.objects.all():
        children = list(goal.children.all())
        if len(children) > 1:
            # Keep first child on original goal
            first_child = children[0]
            goal.child_id = first_child.id
            goal.save()
            
            # Create duplicates for other children
            for child in children[1:]:
                new_goal = ScreenTimeGoal.objects.create(
                    name=goal.name,
                    goal_type=goal.goal_type,
                    reward_minutes=goal.reward_minutes,
                    reward_per_hour=goal.reward_per_hour,
                    bonus_minutes=goal.bonus_minutes,
                    target_minutes=goal.target_minutes,
                    applies_to_days=goal.applies_to_days,
                    is_active=goal.is_active,
                    order=goal.order,
                    child_id=child.id
                )
        elif len(children) == 1:
            goal.child_id = children[0].id
            goal.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_convert_pending_to_notearned"),
    ]

    operations = [
        migrations.RunPython(drop_child_fk_index),
        # If a previous failed run created the M2M through table, drop it to avoid duplicate table errors.
        migrations.RunSQL(sql="DROP TABLE IF EXISTS tracker_goal_children", reverse_sql=""),
        migrations.AlterModelOptions(
            name="screentimegoal",
            options={"ordering": ["order", "name"]},
        ),
        # Add the ManyToMany field first (but don't remove old field yet)
        migrations.AddField(
            model_name="screentimegoal",
            name="children",
            field=models.ManyToManyField(
                help_text="Children this goal applies to",
                related_name="goals_new",  # Use temporary name to avoid conflict
                to="tracker.child",
                db_table="tracker_goal_children",
            ),
        ),
        # Migrate data from child to children
        migrations.RunPython(migrate_child_to_children, reverse_migration),
        # Now remove the old field
        migrations.RemoveField(
            model_name="screentimegoal",
            name="child",
        ),
        # Fix the related_name back to 'goals'
        migrations.AlterField(
            model_name="screentimegoal",
            name="children",
            field=models.ManyToManyField(
                help_text="Children this goal applies to",
                related_name="goals",
                to="tracker.child",
                db_table="tracker_goal_children",
            ),
        ),
    ]
