# Generated by Django 5.0.14 on 2026-01-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_adhocpenalty_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenTimeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of usage")),
                (
                    "minutes_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Minutes of screen time actually used"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes about usage")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_time_usage",
                        to="tracker.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["child", "date"], name="tracker_scr_child_i_a33dbf_idx"
                    )
                ],
                "unique_together": {("child", "date")},
            },
        ),
    ]
