# Generated by Django 5.0.14 on 2026-01-22 15:04

import django.db.models.deletion
from django.db import migrations, models


def populate_child_field(apps, schema_editor):
    """
    Populate the child field in DailyTracking based on the goal's children.
    For goals with multiple children, we need to duplicate the tracking for each child.
    """
    DailyTracking = apps.get_model('tracker', 'DailyTracking')
    
    # Get all existing trackings
    trackings_to_create = []
    trackings_to_update = []
    trackings_to_delete = []
    
    for tracking in DailyTracking.objects.all():
        goal = tracking.goal
        children = list(goal.children.all())
        
        if len(children) == 0:
            # No children assigned to goal - this is an orphan, delete it
            trackings_to_delete.append(tracking.id)
        elif len(children) == 1:
            # Single child - just update this tracking
            tracking.child = children[0]
            trackings_to_update.append(tracking)
        else:
            # Multiple children - keep first child on this tracking, create duplicates for others
            tracking.child = children[0]
            trackings_to_update.append(tracking)
            
            for child in children[1:]:
                trackings_to_create.append(DailyTracking(
                    child=child,
                    goal=tracking.goal,
                    date=tracking.date,
                    status=tracking.status,
                    minutes_earned=tracking.minutes_earned,
                    actual_minutes=tracking.actual_minutes,
                    bonus_earned=tracking.bonus_earned,
                    notes=tracking.notes
                ))
    
    # Apply changes
    DailyTracking.objects.filter(id__in=trackings_to_delete).delete()
    DailyTracking.objects.bulk_update(trackings_to_update, ['child'])
    DailyTracking.objects.bulk_create(trackings_to_create)


def reverse_populate_child_field(apps, schema_editor):
    """
    Reverse migration - remove duplicate trackings for multi-child goals.
    Keep only one tracking per goal+date combination.
    """
    DailyTracking = apps.get_model('tracker', 'DailyTracking')
    
    # Group trackings by goal and date
    seen = set()
    to_delete = []
    
    for tracking in DailyTracking.objects.all().order_by('goal', 'date', 'id'):
        key = (tracking.goal_id, tracking.date)
        if key in seen:
            to_delete.append(tracking.id)
        else:
            seen.add(key)
    
    DailyTracking.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_convert_goal_to_many_children"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dailytracking",
            name="tracker_dai_date_7144ef_idx",
        ),
        migrations.AlterUniqueTogether(
            name="dailytracking",
            unique_together=set(),
        ),
        # Add child field as nullable first
        migrations.AddField(
            model_name="dailytracking",
            name="child",
            field=models.ForeignKey(
                null=True,
                help_text="Child this tracking belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_trackings",
                to="tracker.child",
            ),
        ),
        # Populate the child field
        migrations.RunPython(populate_child_field, reverse_populate_child_field),
        # Make child field non-nullable
        migrations.AlterField(
            model_name="dailytracking",
            name="child",
            field=models.ForeignKey(
                help_text="Child this tracking belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_trackings",
                to="tracker.child",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailytracking",
            unique_together={("child", "goal", "date")},
        ),
        migrations.AddIndex(
            model_name="dailytracking",
            index=models.Index(
                fields=["child", "date", "goal"], name="tracker_dai_child_i_510029_idx"
            ),
        ),
    ]
