# Generated by Django 5.0.14 on 2026-01-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_screentimeusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adhocpenalty",
            name="applied_date",
            field=models.DateField(help_text="Date the penalty was applied"),
        ),
        migrations.AlterField(
            model_name="adhocreward",
            name="awarded_date",
            field=models.DateField(help_text="Date the reward was given"),
        ),
    ]
