# Generated by Django 5.0.14 on 2026-01-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_adhocpenalty_applied_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="screentimeusage",
            unique_together=set(),
        ),
    ]
