# Generated by Django 5.0.14 on 2026-01-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_alter_screentimeusage_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="screentimegoal",
            name="rollover_sunday_to_next_week",
            field=models.BooleanField(
                default=False,
                help_text="If earned on Sunday, apply the reward to the following week's totals",
            ),
        ),
    ]
